
# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
   - 2.11.11
   - 2.12.2
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - tom@sfxcode.com
jdk:
  - oraclejdk8
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
addons:
  apt:
    packages:
      - oracle-java8-installer
script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts test